# Sync Runtime - Runtime File Synchronization Utility
name: "sync-runtime"
description: "Sync bmad/ source files to .claude/commands/ runtime location with 3-way conflict detection and resolution options"
author: "BMAD Core"

# Critical variables from config
config_source: "{project-root}/bmad/core/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Module path and component files
installed_path: "{project-root}/bmad/core/workflows/sync-runtime"
template: false
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Web bundle configuration
web_bundle: false # Core workflows run locally in project context
