# Review Quality Workflow - GSAP Excellence Engine
# THE ULTIMATE QUALITY GATE: Comprehensive 6-Part Excellence Assessment
# Agent: Director
# Complexity: High (39 Deep-Research sections, multi-source research)

name: review-quality
description: "THE ULTIMATE QUALITY GATE: Comprehensive 6-part excellence assessment (Creative, Technical, Patterns, Performance, Accessibility, Pitfalls) with 39 Deep-Research sections + Archon MCP + WebSearch validation"
author: "GSAP Excellence Engine - The Director"
version: "2.0.0-premium"
complexity: "high"
standalone: false  # Agent-context-dependent workflow (only callable from Director agent menu)

# Standard config block (REQUIRED - provides communication_language, user_name, date, output_folder)
config_source: "{project-root}/bmad/gsap-excellence/config.yaml"
module_root: "{project-root}/bmad/gsap-excellence"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
output_folder: "{config_source}:output_folder"
date: system-generated
timestamp: system-generated

# Workflow Metadata
metadata:
  agent: 'gsap-director'
  priority: 'P0'  # Highest priority - final quality gate before production
  research_intensity: 'extreme'  # 39 Deep-Research sections + Archon + WebSearch
  estimated_duration: '45-60 minutes'
  persona: 'film-director-quality-control'
  assessment_approach: 'multi-dimensional-systematic'
  quality_categories: 6  # Creative, Technical, Patterns, Performance, Accessibility, Pitfalls

# Required MCP Servers
required_mcp:
  - archon  # GSAP knowledge base (89 sources) - Premium pattern benchmarking
  - chrome_devtools  # Performance profiling, accessibility validation (conditional)

# Deep-Research Sections Referenced (39 TOTAL - Most comprehensive workflow!)
deep_research_sections:
  # CATEGORY 1: Creative Excellence (6 sections)
  - '1.1'  # Animator's Mindset vs Code Generator (CORE)
  - '1.2'  # Visual Inspiration → Technical Translation (CORE)
  - '1.3'  # Storyboarding Complex Sequences
  - '1.4'  # Decision Framework: GSAP vs Alternatives (CORE)
  - '4.1'  # Pixar Story Spine Framework (CORE)
  - '4.2'  # Alternative Narrative Structures

  # CATEGORY 2: Technical Mastery (6 sections)
  - '2.1'  # Core GSAP Concepts (tween, timeline, stagger, ease)
  - '2.2'  # Timeline Techniques (CORE)
  - '2.3'  # Plugin Ecosystem (ALL FREE since 2024!)
  - '2.4'  # Performance Patterns & Optimization
  - '2.5'  # Integration Patterns (React/Next.js/Vue)
  - '2.6'  # Additional Advanced Techniques

  # CATEGORY 3: Implementation Patterns (7 sections)
  - '3.1'  # Smooth Page Load Sequence
  - '3.2'  # Content Reveal on Scroll (ScrollTrigger basics)
  - '3.3'  # Sticky Scroll + Pinning + Parallax
  - '3.4'  # Staggered Grid Reveal
  - '3.5'  # Text Split & Reveal (SplitText plugin)
  - '3.6'  # FLIP for State Transitions
  - '3.7'  # Cleanup & Reinitialization

  # CATEGORY 4: Performance Excellence (6 sections)
  - '5.1'  # GPU Rule (transform/opacity only!)
  - '5.2'  # Main Thread Free (avoid long tasks)
  - '5.3'  # Debugging Jank
  - '5.4'  # Memory Management & Garbage Collection
  - '5.5'  # Optimize for 60fps
  - '5.6'  # When to use WebGL/Canvas

  # CATEGORY 5: Accessibility Excellence (4 sections)
  - '6.1'  # prefers-reduced-motion (MANDATORY!)
  - '6.2'  # Other Motion Accessibility
  - '6.3'  # Styling Considerations for Motion
  - '6.4'  # User Control & Education

  # CATEGORY 6: Pitfall Avoidance (10 sections)
  - '8.1'  # Memory leaks & double animations
  - '8.2'  # Animating wrong properties (no GPU acceleration)
  - '8.3'  # Ignoring .from vs .fromTo tweens
  - '8.4'  # Multiple ScrollTriggers on same element
  - '8.5'  # Not using overwrite causing conflicts
  - '8.6'  # Overlooking ScrollTrigger.refresh() after content load
  - '8.7'  # Use of deprecated or old syntax
  - '8.8'  # Uncontrolled infinite loops
  - '8.9'  # Not testing on different devices
  - '8.10' # Misusing .set() vs .fromTo() causing flicker

# Archon Priority Sources (Premium Quality Benchmarks)
archon_sources:
  - 'b9f6b322298feb21'  # gsap.com official docs (PRIMARY)
  - '6a6860cfc96e173b'  # ScrollTrigger official docs
  - '1e5cc3bd5125be3c'  # Codrops GSAP tutorials (quality patterns)
  - '32-75'  # Notable Agencies & Patterns (Deep-Research 7.5)
  - 'awwwards'  # Premium site examples (WebSearch target)

# Deep-Research Knowledge Base (GSAP Animation Mastery - 43 core sections)
deep_research_base: '{project-root}/docs/Deep-Research/GSAP-Animation-Mastery'

# Quality-specific Deep-Research files (39 sections across 6 categories):
# Category 1 - Creative Excellence:
# - 01-11-the-animators-mindset-vs-code-generator.md
# - 02-12-visual-inspiration-technical-translation-workflow.md
# - 03-13-storyboarding-complex-sequences.md
# - 04-14-deciding-between-gsap-and-alternatives.md
# - 04-41-pixar-story-spine-framework-for-gsap.md
# - 04-42-alternative-narrative-structures.md
#
# Category 2 - Technical Mastery:
# - 05-21-core-gsap-concepts-tween-timeline-stagger-ease.md
# - 06-22-mastering-gsap-timeline-techniques.md
# - 07-23-the-2024-gsap-plugin-ecosystem-all-free.md
# - 08-24-performance-patterns-and-optimization-techniques.md
# - 09-25-integration-patterns-gsap-react-nextjs-other-frameworks.md
# - 10-26-additional-advanced-techniques.md
#
# Category 3 - Implementation Patterns:
# - 11-31-pattern-smooth-page-load-sequence-intro-timeline.md
# - 12-32-pattern-content-reveal-on-scroll-scrolltrigger-basics.md
# - 13-33-pattern-sticky-scroll-triggered-animation-pinning-parallax.md
# - 14-34-pattern-staggered-grid-reveal-with-advanced-staggering-grid-from-options.md
# - 15-35-pattern-text-split-and-reveal-splittext-fancy-effect.md
# - 16-36-pattern-using-flip-for-state-transitions-eg-image-grid-to-lightbox.md
# - 17-37-pattern-cleanup-and-reinitialization-fullpage-transitions.md
#
# Category 4 - Performance Excellence:
# - 18-51-animate-efficient-properties-the-gpu-rule.md
# - 19-52-keep-the-main-thread-free-avoid-long-tasks.md
# - 20-53-debugging-jank.md
# - 21-54-memory-management-garbage-collection.md
# - 22-55-optimize-animations-for-60fps.md
# - 23-56-when-to-use-webglcanvas.md
#
# Category 5 - Accessibility Excellence:
# - 24-61-respecting-prefers-reduced-motion.md
# - 25-62-other-motion-accessibility-considerations.md
# - 26-63-styling-considerations-for-motion.md
# - 27-64-educate-users-and-offer-control.md
#
# Category 6 - Pitfall Avoidance:
# - 34-pitfall-81-forgetting-to-clean-up-memory-leaks-double-animations.md
# - 35-pitfall-82-animating-the-wrong-properties-no-gpu-acceleration.md
# - 36-pitfall-83-ignoring-in-from-tweens.md
# - 37-pitfall-84-multiple-scrolltriggers-on-the-same-elements-property.md
# - 38-pitfall-85-not-using-leading-to-conflict.md
# - 39-pitfall-86-overlooking-refresh-after-content-load.md
# - 40-pitfall-87-use-of-deprecated-or-old-syntax.md
# - 41-pitfall-88-uncontrolled-infinite-loops.md
# - 42-pitfall-89-not-testing-on-different-devices.md
# - 43-pitfall-810-misusing-vs-causing-flicker.md

# Chrome DevTools Integration (CONDITIONAL - for performance/accessibility deep-dive)
chrome_devtools_capabilities:
  - take_screenshot  # Visual quality capture
  - list_console_messages  # Error detection
  - performance_start_trace  # Performance profiling (if concerns mentioned)
  - emulate_cpu  # CPU throttle testing (if performance concerns)

agents:
  primary: "gsap-director"
  supporting:
    - "gsap-cinematographer"  # Pattern research specialist
    - "gsap-tech-director"  # Performance validation
    - "gsap-editor"  # Timing refinement
    - "gsap-vfx"  # Implementation patterns

installed_path: "{module_root}/workflows/review-quality"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

default_output_file: "{output_folder}/quality-review-{timestamp}.md"

inputs:
  animation_description:
    description: "What should this animation do? (Specific behavior and intent)"
    required: true
    type: "descriptive_text"

  current_implementation:
    description: "Current GSAP code OR detailed description"
    required: true
    type: "code_or_description"

  animation_type:
    description: "Animation category (hero section / scroll narrative / micro-interaction / page transition / product showcase / other)"
    required: true
    type: "classification"

  specific_concerns:
    description: "Areas to focus on (performance / timing / wow-factor / accessibility / code quality / other)"
    required: false
    type: "multi_select"

  target_audience:
    description: "Who experiences this animation? (general public / premium brand / developers / gaming / b2b)"
    required: false
    type: "classification"

  device_targets:
    description: "Target devices (desktop-only / mobile-first / both / high-end-only)"
    required: false
    type: "classification"

outputs:
  quality_tier_assessment:
    format: "Tier 1 (Museum-Grade) / Tier 2 (Professional) / Tier 3 (Basic)"
    type: "classification"

  creative_excellence_score:
    format: "6-part assessment (Animator's Mindset, Visual Translation, Tool Selection, etc.)"
    type: "structured_analysis"

  technical_mastery_score:
    format: "6-part assessment (GSAP proficiency, timeline techniques, plugin usage, etc.)"
    type: "structured_analysis"

  pattern_implementation_score:
    format: "7-part assessment (page load, scroll reveal, stagger, text, FLIP, cleanup, etc.)"
    type: "structured_analysis"

  performance_excellence_score:
    format: "6-part assessment (GPU usage, main thread, jank, memory, 60fps, WebGL)"
    type: "structured_analysis"

  accessibility_excellence_score:
    format: "4-part assessment (prefers-reduced-motion, other a11y, styling, user control)"
    type: "structured_analysis"

  pitfall_avoidance_score:
    format: "10-part audit (memory, properties, syntax, conflicts, testing, etc.)"
    type: "structured_analysis"

  archon_premium_patterns:
    format: "10-15 premium patterns benchmarked (Tier 1/2/3 classification)"
    type: "research_findings"

  improvement_recommendations:
    format: "Prioritized list (HIGH/MEDIUM/LOW impact) with Deep-Research citations"
    type: "actionable_guidance"

  research_citations:
    format: "All Archon sources, Deep-Research sections, WebSearch URLs used"
    type: "documentation"

success_criteria:
  - "All 6 quality categories assessed (Creative, Technical, Patterns, Performance, Accessibility, Pitfalls)"
  - "Research-backed assessment (minimum 10 Archon patterns + 5 Deep-Research sections consulted)"
  - "MANDATORY research gates completed (cannot skip)"
  - "Quality tier assigned (Tier 1/2/3) with gap analysis"
  - "Actionable recommendations with citations (HIGH/MEDIUM/LOW priority)"
  - "Zero anti-patterns or red flags = excellence confirmed"

estimated_duration: "45-60 minutes (comprehensive multi-dimensional assessment)"

web_bundle:
  name: 'review-quality'
  description: 'THE ULTIMATE QUALITY GATE: Comprehensive 6-part excellence assessment with 39 Deep-Research sections'
  path: 'bmad/gsap-excellence/workflows/review-quality'
  web_bundle_files:
    - 'bmad/gsap-excellence/workflows/review-quality/workflow.yaml'
    - 'bmad/gsap-excellence/workflows/review-quality/instructions.md'
    - 'bmad/gsap-excellence/workflows/review-quality/template.md'
    - 'bmad/gsap-excellence/workflows/review-quality/checklist.md'
