# GSAP Excellence Engine v2 - Module Configuration
# Rebuild with proper orchestration architecture
# Version: 2.0.0-alpha.0
# Date: 2025-10-14

# Core Configuration
user_name: Cameron
communication_language: English
output_folder: '{project-root}/docs'
module_root: '{project-root}/bmad/gsap-excellence-v2'
pattern_library: '{module_root}/patterns'

# Module Metadata
module:
  name: "GSAP Excellence Engine v2"
  code: "gsap-excellence-v2"
  version: "2.0.0-alpha.0"
  author: "Cameron"
  description: "Premium GSAP animation production with automated orchestration"
  category: "technical"
  complexity: "complex"
  created: "2025-10-14"

# MCP Server Requirements
mcp_servers:
  archon:
    required: true
    purpose: "GSAP documentation RAG database"
    tools:
      - rag_search_knowledge_base
      - rag_search_code_examples
      - rag_get_available_sources
    fallback: "Continue with other sources"

  context7:
    required: true
    purpose: "Latest GSAP API documentation"
    tools:
      - resolve-library-id
      - get-library-docs
    fallback: "Use cached version info"

  perplexity:
    required: true
    purpose: "Premium animation examples and trends"
    tools:
      - perplexity_ask
      - perplexity_reason
      - perplexity_research
    fallback: "Use Archon examples only"

  chrome_devtools:
    required: false
    purpose: "Performance profiling and visual testing"
    tools:
      - take_screenshot
      - list_console_messages
      - performance_start_trace
      - performance_stop_trace
      - performance_analyze_insight
      - emulate_cpu
      - emulate_network
    fallback: "Manual performance testing required"

# Agents (1 Main Agent)
agents:
  gsap_studio:
    file: "agents/gsap-studio.md"
    name: "GSAP Studio"
    role: "Complete GSAP animation expert and orchestrator"
    icon: "🎬"
    personality: "Professional, results-focused, minimal ceremony"
    capabilities:
      - "Multi-source research (3 MCPs)"
      - "Pattern library integration"
      - "Task tool orchestration"
      - "Performance validation"
      - "Production-ready implementations"

# Workflows
workflows:
  produce_animation:
    path: "workflows/produce-animation"
    name: "Produce Animation"
    description: "Complete automated pipeline from concept to production"
    complexity: "complex"
    flagship: true
    estimated_time: "30-60 minutes"
    uses_task_tool: true
    uses_mcps: ["archon", "context7", "perplexity", "chrome_devtools"]

  research_pattern:
    path: "workflows/research-pattern"
    name: "Research Pattern"
    description: "Deep dive research into GSAP technique"
    complexity: "standard"
    estimated_time: "5-10 minutes"
    uses_mcps: ["archon", "context7", "perplexity"]

  implement_animation:
    path: "workflows/implement-animation"
    name: "Implement Animation"
    description: "Build animation from pattern or concept"
    complexity: "standard"
    estimated_time: "10-20 minutes"
    can_use_task_tool: true

  optimize_performance:
    path: "workflows/optimize-performance"
    name: "Optimize Performance"
    description: "Profile and optimize existing animation"
    complexity: "standard"
    estimated_time: "10-15 minutes"
    uses_mcps: ["chrome_devtools"]

# Quality Standards
quality_standards:
  performance:
    target_fps: 60
    cpu_throttle_test: "4x slowdown"
    paint_time_budget: "16ms per frame"
    js_execution_budget: "5ms per frame"

  accessibility:
    reduced_motion_required: true
    keyboard_accessible: true
    focus_management: "if interactive"

  code_quality:
    cleanup_required: true
    no_console_errors: true
    typescript_typed: "if applicable"
    no_placeholders: true

  browser_support:
    - "Chrome (latest 2 versions)"
    - "Firefox (latest 2 versions)"
    - "Safari (latest 2 versions)"

# Success Metrics
success_metrics:
  automation:
    target: "0 manual agent switches"
    baseline: "4-5 switches in v1"

  time_to_result:
    simple_animation: "3-5 minutes"
    complete_production: "30-60 minutes"
    baseline_v1: "45-90+ minutes with overhead"

  first_time_success:
    target: "60%+"
    baseline: "20%"

  performance_achievement:
    target: "90%+ achieve 60fps"

  user_satisfaction:
    target: "This actually saves time"
    baseline_v1: "Adds complexity"

# Pattern Library
pattern_library:
  location: "patterns/"
  format: "YAML"
  count: 12
  categories:
    - scroll-effects
    - timelines
    - text-animations
    - interactive
  searchable: true
  browsable: true
  recommendable: true
