# SVG Morph Animation Workflow (PREMIUM)
# VFX Artist - MorphSVGPlugin implementation with research-backed patterns
# Version: 2.0.0-premium
# Lines: ~180 (premium quality with comprehensive configuration)

name: 'create-morph-animation'
version: '2.0.0-premium'
description: 'Create cinematic SVG shape morphing animations using MorphSVGPlugin (FREE in GSAP 3.13+) with research-backed patterns, point optimization, and performance precompile techniques'
author: 'VFX Artist'

# Installation paths
installed_path: '{project-root}/bmad/gsap-excellence/workflows/create-morph-animation'
instructions: '{installed_path}/instructions.md'
template: null  # Generates code directly (no document template needed)
validation: '{installed_path}/checklist.md'
default_output_file: null  # Code output only (no report file)

# Standard config block (REQUIRED - provides communication_language, user_name, date, output_folder)
config_source: '{project-root}/bmad/gsap-excellence/config.yaml'
output_folder: '{config_source}:output_folder'
user_name: '{config_source}:user_name'
communication_language: '{config_source}:communication_language'
date: system-generated

# Execution mode
standalone: false  # Agent-context-dependent workflow (only callable from VFX agent menu)
autonomous: false  # Requires user input and research gate approvals

# Workflow metadata
metadata:
  agent: 'vfx'
  priority: 'P2'  # Important animation technique (icon transitions, brand animations)
  complexity: 'medium'  # MorphSVG is powerful but needs path optimization understanding
  research_intensity: 'medium'  # Section 2.3 + Archon MCP pattern research
  estimated_duration: '15-25 minutes'  # Including research phase + implementation + testing
  output_type: 'code'  # Direct code generation (React/Next.js/Vue compatible)
  skill_level: 'intermediate'  # Requires SVG path understanding and optimization awareness

# Required MCP Servers (MANDATORY for research gates)
required_mcp:
  - archon  # MorphSVG code examples, pattern matching, point optimization techniques
  - context7  # Latest MorphSVGPlugin API documentation (GSAP 3.13+ features)

# Deep-Research Sections Referenced (MANDATORY reading in workflow)
deep_research_sections:
  - '2.3'  # The 2024 GSAP Plugin Ecosystem - All FREE (PERFECT MATCH for MorphSVG FREE status)

# Deep-Research Knowledge Base
deep_research_base: '{project-root}/docs/Deep-Research/GSAP-Animation-Mastery'

# Archon MCP Priority Sources (gsap.com official docs + performance guides)
archon_sources:
  - 'b9f6b322298feb21'  # gsap.com official documentation (MorphSVGPlugin, convertToPath, shapeIndex optimization)
  - '6a6860cfc96e173b'  # GSAP performance and ScrollTrigger documentation

# MorphSVG Plugin Status (CRITICAL: FREE since GSAP 3.13+)
plugin_status:
  name: 'MorphSVGPlugin'
  availability: 'FREE in GSAP 3.13+ (was paid plugin before Webflow acquisition in October 2024)'
  licensing: 'Completely free with standard GSAP installation'
  reference_url: 'https://gsap.com/blog/gsap-3-13-0-release'
  reference_section: 'Section 2.3 documents the FREE plugin ecosystem transformation'
  breaking_change: 'No breaking changes - existing MorphSVG code works unchanged'

# Morph Animation Categories (Pattern Taxonomy)
morph_categories:
  icon_morphing:
    description: 'UI icon transitions (menu ↔ X, play ↔ pause, heart ↔ star)'
    use_cases:
      - 'Navigation toggles (hamburger menu → X close icon)'
      - 'Media controls (play → pause button morphing)'
      - 'State indicators (checkbox → checkmark, heart → filled heart)'
    complexity: 'low'
    typical_duration: '0.3-0.6 seconds'
    recommended_easing: 'power2.inOut, elastic.out(1, 0.5), back.out(1.7)'

  shape_transitions:
    description: 'Geometric shape transformations (circle → square → triangle → star)'
    use_cases:
      - 'Brand shape animations (logo reveals, loading states)'
      - 'Data visualization morphing (chart type transitions)'
      - 'Educational animations (geometry demonstrations)'
    complexity: 'low-medium'
    typical_duration: '0.8-1.5 seconds'
    recommended_easing: 'power2.inOut, circ.out, expo.inOut'

  blob_morphing:
    description: 'Organic, liquid shape morphing (amoeba-like blob animations)'
    use_cases:
      - 'Background decorative elements (hero section blobs)'
      - 'Loading animations (pulsing organic shapes)'
      - 'Interactive hover effects (shape breathing, pulsing)'
    complexity: 'medium'
    typical_duration: '2-4 seconds (often with repeat: -1, yoyo: true)'
    recommended_easing: 'sine.inOut, power1.inOut, none (for smooth loops)'

  text_to_shape:
    description: 'Letter/word morphing into shapes or icons'
    use_cases:
      - 'Brand storytelling (letter transforming into logo)'
      - 'Typography reveals (text becoming illustrations)'
      - 'Creative transitions (word morphing into visual metaphor)'
    complexity: 'high'
    typical_duration: '1-2 seconds'
    recommended_easing: 'power3.out, expo.out, elastic.out'

  multi_stage:
    description: 'Complex sequences with 3+ morphing stages (A → B → C → D)'
    use_cases:
      - 'Storytelling sequences (visual narrative progression)'
      - 'Product feature tours (shape representing different features)'
      - 'Loading sequences (multi-stage loading animation)'
    complexity: 'medium-high'
    typical_duration: '3-8 seconds total (0.8-1.5s per stage)'
    recommended_easing: 'power2.inOut (consistency across stages)'

# Path Optimization Techniques (Research-Backed)
path_optimization:
  convertToPath:
    description: 'Convert basic SVG shapes (circle, rect, polygon, ellipse) to <path> elements'
    when_to_use: 'ALWAYS convert before morphing - MorphSVG requires <path> elements'
    method: 'MorphSVGPlugin.convertToPath("circle, rect, polygon, ellipse")'
    performance_impact: 'One-time conversion at initialization (minimal impact)'

  shapeIndex:
    description: 'Control point alignment/rotation for optimal morphing'
    options:
      auto: 'MorphSVGPlugin calculates best alignment automatically (default, recommended for most cases)'
      log: 'Console.log the calculated shapeIndex array for precompile optimization'
      specific_array: 'Use precomputed array like [3] for production performance (skip runtime calculation)'
    when_to_use: 'Use "auto" during development, "log" → precompile for production'
    performance_gain: 'Precompiled shapeIndex eliminates runtime calculation (significant for complex paths)'

  precompile:
    description: 'Pre-calculate morphed path strings for maximum performance'
    method: 'Set morphSVG: { shape: "#target", precompile: "log" } to log precompiled strings'
    use_case: 'Production animations with complex paths (100+ points) or repeated morph instances'
    performance_gain: '50-80% faster tween start (eliminates expensive path interpolation calculations)'
    trade_off: 'Larger bundle size (storing precompiled strings) vs runtime CPU savings'

  point_count_matching:
    description: 'Similar point counts between start/end shapes produce smoother morphs'
    recommendation: 'Aim for similar complexity (within 20% point count difference)'
    tool_support: 'MorphSVGPlugin auto-adjusts point counts, but similar counts = better quality'
    visual_impact: 'Drastically different point counts can cause unexpected "twisting" during morph'

# Performance Considerations (Research-Backed)
performance:
  typical_60fps_capability:
    description: 'MorphSVG can handle 60fps morphing on modern devices'
    path_complexity_limit: 'Up to ~200 points per path on desktop, ~100 points on mobile for smooth 60fps'
    concurrent_morphs: '5-10 simultaneous morphs typically maintain 60fps (device-dependent)'

  optimization_strategies:
    - 'Use precompile for production (eliminates runtime path calculations)'
    - 'Use shapeIndex arrays instead of "auto" in production (skip alignment calculation)'
    - 'Simplify SVG paths before morphing (use Illustrator path simplify or svgo)'
    - 'Use will-change: transform on morphing elements (GPU acceleration hint)'
    - 'Avoid morphing extremely complex paths (500+ points) - consider alternative techniques'

  combined_effects:
    description: 'MorphSVG works well with other GSAP plugins'
    compatible_plugins:
      - 'DrawSVG: Morph + progressive stroke reveal (cinematic effect)'
      - 'MotionPath: Morph shape while moving along path'
      - 'ScrollTrigger: Scroll-driven shape morphing'
    performance_note: 'Multiple simultaneous plugins increase CPU load - test on target devices'

# Framework Integration Patterns
framework_integration:
  react:
    hook_usage: 'Use useGSAP() hook from @gsap/react for lifecycle-safe morphing'
    ref_pattern: 'useRef() for SVG element references, avoid direct DOM queries'
    cleanup: 'CRITICAL: Kill morphing tweens in cleanup function to prevent memory leaks'

  nextjs:
    import_method: 'Dynamic import with ssr: false for MorphSVGPlugin (client-side only)'
    hydration: 'Ensure morphing initializes after hydration (useEffect with mounted check)'

  vue:
    lifecycle: 'Use onMounted() for morphing initialization, onBeforeUnmount() for cleanup'
    ref_usage: 'Vue template refs for SVG element access'

  vanilla:
    initialization: 'Initialize after DOM ready (DOMContentLoaded or defer script)'
    cleanup: 'Store tween references and kill() on page navigation'

# SVG Requirements (Technical Specifications)
svg_requirements:
  path_elements_only:
    description: 'MorphSVG requires <path> elements (not <circle>, <rect>, etc.)'
    solution: 'Use MorphSVGPlugin.convertToPath() to convert shapes'

  similar_complexity:
    description: 'Start and end shapes should have similar point counts for smooth morphing'
    recommendation: 'Within 20% point count difference for best visual quality'

  viewBox_consistency:
    description: 'Maintain consistent SVG viewBox for predictable morphing'
    best_practice: 'Use same viewBox dimensions for all morphing shapes'

  path_data_format:
    description: 'Clean, well-formed SVG path data (no parsing errors)'
    validation: 'Use SVG validators or test in browser DevTools before morphing'

# Common Patterns (Research-Backed from Archon MCP)
common_patterns:
  simple_morph:
    code: 'gsap.to("#shape1", { morphSVG: "#shape2", duration: 1, ease: "power2.inOut" })'
    use_case: 'Basic icon transitions, single-stage morphing'

  timeline_sequence:
    code: 'const tl = gsap.timeline(); tl.to("#shape", { morphSVG: "#circle" }).to("#shape", { morphSVG: "#square" })'
    use_case: 'Multi-stage morphing (3+ shapes in sequence)'

  blob_loop:
    code: 'gsap.to("#blob", { morphSVG: { shape: "#target", shapeIndex: "auto" }, duration: 2, ease: "sine.inOut", repeat: -1, yoyo: true })'
    use_case: 'Organic background blobs, pulsing shapes'

  optimized_production:
    code: 'gsap.to("#icon", { morphSVG: { shape: "#target", shapeIndex: [3], precompile: ["M0,0 C100...", "M0,0 C200..."] }, duration: 0.4 })'
    use_case: 'Production-ready with precompiled values (maximum performance)'

# Testing Checklist Categories
testing_categories:
  visual_quality:
    - 'Smooth morphing (no distortion, twisting, or unexpected paths)'
    - 'Timing feels natural (not too fast or too slow)'
    - 'Easing creates organic feel (matches animation category recommendations)'

  technical_compliance:
    - 'Using <path> elements (not shapes - converted via convertToPath if needed)'
    - 'Similar point counts between start/end shapes'
    - 'shapeIndex optimization applied (auto for dev, precompile for prod)'

  performance:
    - 'Maintains 60fps on target devices (desktop + mobile)'
    - 'No memory leaks (tweens killed on cleanup)'
    - 'Bundle size reasonable (precompiled strings don't bloat excessively)'

  accessibility:
    - 'Respects prefers-reduced-motion (disable or simplify morphing)'
    - 'Keyboard navigable if interactive (focus states visible)'
    - 'Screen reader friendly (ARIA labels for semantic meaning)'

# Web Bundle Configuration (Self-Contained Package)
web_bundle:
  name: 'create-morph-animation'
  description: 'Premium MorphSVG workflow with research-backed patterns'
  author: 'VFX Artist'

  # Core files (bmad/-relative paths for web deployment)
  instructions: 'bmad/gsap-excellence/workflows/create-morph-animation/instructions.md'
  validation: 'bmad/gsap-excellence/workflows/create-morph-animation/checklist.md'

  # Complete file manifest (CRITICAL for web bundle completeness)
  files:
    - 'bmad/gsap-excellence/workflows/create-morph-animation/workflow.yaml'
    - 'bmad/gsap-excellence/workflows/create-morph-animation/instructions.md'
    - 'bmad/gsap-excellence/workflows/create-morph-animation/checklist.md'

  # Dependencies (external files needed)
  dependencies:
    - 'bmad/gsap-excellence/config.yaml'  # Standard config (user_name, output_folder, etc.)

  # Required MCP servers for web deployment
  mcp_servers:
    - 'archon'  # MorphSVG pattern research
    - 'context7'  # Latest GSAP API docs

  standalone: false  # Requires VFX agent context
