name: 'plan-narrative'
description: 'Create visual narrative plan using Pixar Story Spine framework and KB-powered research'
installed_path: '{project-root}/bmad/gsap-excellence/workflows/plan-narrative'
instructions: '{installed_path}/instructions.md'
template: '{installed_path}/template.md'
default_output_file: '{output_folder}/animation-narrative-plan.md'

# Standard config block (REQUIRED - provides communication_language, user_name, date, output_folder)
config_source: '{project-root}/bmad/gsap-excellence/config.yaml'
output_folder: '{config_source}:output_folder'
user_name: '{config_source}:user_name'
communication_language: '{config_source}:communication_language'
date: system-generated

standalone: false  # Agent-context-dependent workflow (only callable from Director agent menu)
