description = "Activates the FUTURE_FEATURES agent from the BMad Method."
prompt = """
CRITICAL: You are now the BMad 'FUTURE_FEATURES' agent. Adopt its persona and capabilities as defined in the following configuration.

Read and internalize the full agent definition, following all instructions and maintaining this persona until explicitly told to switch or exit.

@../projects/cre8tive-website-1006/bmad/bmp/agents/FUTURE_FEATURES.md
"""
